-- 球员17-24号数据

-- 球员17: 重庆 中场
INSERT INTO users (id, phone, password, nickname, avatar, role, status, name, birth_date, age, gender, height, weight, foot, position, second_position, start_year, country, province, city, club, fa_registered, association, jersey_color, jersey_number, father_height, father_phone, father_edu, father_job, father_athlete, mother_height, mother_phone, mother_edu, mother_job, mother_athlete, created_at, updated_at) 
VALUES (17, '13800110017', '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqWjW7e7VJhRj0XkP9QxKxW.KqE9a', '山城魔术师', 'https://api.dicebear.com/7.x/avataaars/svg?seed=player17', 'user', 'active', '谢云飞', '2010-07-18', 15, 'male', 174.0, 65.0, 'both', '中场', '全能中场', 2019, '中国', '重庆', '重庆', '重庆当代青训', 1, '重庆市足球协会', '红', 10, 176.0, '15700111123', '本科', '餐饮老板', 0, 162.0, '15700222234', '高中', '美容师', 0, datetime('now'), datetime('now'));

-- 球员18: 天津 后卫
INSERT INTO users (id, phone, password, nickname, avatar, role, status, name, birth_date, age, gender, height, weight, foot, position, second_position, start_year, country, province, city, club, fa_registered, association, jersey_color, jersey_number, father_height, father_phone, father_edu, father_job, father_athlete, mother_height, mother_phone, mother_edu, mother_job, mother_athlete, created_at, updated_at) 
VALUES (18, '13800110018', '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqWjW7e7VJhRj0XkP9QxKxW.KqE9a', '津门铁闸', 'https://api.dicebear.com/7.x/avataaars/svg?seed=player18', 'user', 'active', '马俊豪', '2009-04-25', 16, 'male', 183.0, 76.0, 'right', '后卫', '中后卫', 2018, '中国', '天津', '天津', '天津津门虎青训', 1, '天津市足球协会', '紫白', 4, 186.0, '15600111124', '本科', '机械工程师', 0, 168.0, '15600222235', '本科', '护士', 0, datetime('now'), datetime('now'));

-- 球员19: 河南郑州 前锋
INSERT INTO users (id, phone, password, nickname, avatar, role, status, name, birth_date, age, gender, height, weight, foot, position, second_position, start_year, country, province, city, club, fa_registered, association, jersey_color, jersey_number, father_height, father_phone, father_edu, father_job, father_athlete, mother_height, mother_phone, mother_edu, mother_job, mother_athlete, created_at, updated_at) 
VALUES (19, '13800110019', '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqWjW7e7VJhRj0XkP9QxKxW.KqE9a', '中原神锋', 'https://api.dicebear.com/7.x/avataaars/svg?seed=player19', 'user', 'active', '韩宇轩', '2010-02-08', 15, 'male', 177.0, 70.0, 'left', '前锋', '中锋', 2019, '中国', '河南', '郑州', '河南嵩山龙门青训', 1, '河南省足球协会', '红', 9, 180.0, '15500111125', '本科', '销售经理', 1, 165.0, '15500222236', '高中', '个体户', 0, datetime('now'), datetime('now'));

-- 球员20: 湖南长沙 中场
INSERT INTO users (id, phone, password, nickname, avatar, role, status, name, birth_date, age, gender, height, weight, foot, position, second_position, start_year, country, province, city, club, fa_registered, association, jersey_color, jersey_number, father_height, father_phone, father_edu, father_job, father_athlete, mother_height, mother_phone, mother_edu, mother_job, mother_athlete, created_at, updated_at) 
VALUES (20, '13800110020', '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqWjW7e7VJhRj0XkP9QxKxW.KqE9a', '星城指挥官', 'https://api.dicebear.com/7.x/avataaars/svg?seed=player20', 'user', 'active', '唐子墨', '2009-11-30', 16, 'male', 175.5, 68.5, 'right', '中场', '组织中场', 2018, '中国', '湖南', '长沙', '湖南湘涛青训', 1, '湖南省足球协会', '蓝白', 7, 178.0, '15400111126', '本科', '公务员', 0, 164.0, '15400222237', '本科', '教师', 0, datetime('now'), datetime('now'));

-- 球员21: 河北石家庄 后卫
INSERT INTO users (id, phone, password, nickname, avatar, role, status, name, birth_date, age, gender, height, weight, foot, position, second_position, start_year, country, province, city, club, fa_registered, association, jersey_color, jersey_number, father_height, father_phone, father_edu, father_job, father_athlete, mother_height, mother_phone, mother_edu, mother_job, mother_athlete, created_at, updated_at) 
VALUES (21, '13800110021', '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqWjW7e7VJhRj0XkP9QxKxW.KqE9a', '燕赵铁卫', 'https://api.dicebear.com/7.x/avataaars/svg?seed=player21', 'user', 'active', '冯子涵', '2010-05-15', 15, 'male', 181.0, 74.0, 'left', '后卫', '左后卫', 2019, '中国', '河北', '石家庄', '河北华夏幸福青训', 1, '河北省足球协会', '红', 3, 184.0, '15300111127', '本科', '医生', 0, 167.0, '15300222238', '本科', '药剂师', 0, datetime('now'), datetime('now'));

-- 球员22: 安徽合肥 前锋
INSERT INTO users (id, phone, password, nickname, avatar, role, status, name, birth_date, age, gender, height, weight, foot, position, second_position, start_year, country, province, city, club, fa_registered, association, jersey_color, jersey_number, father_height, father_phone, father_edu, father_job, father_athlete, mother_height, mother_phone, mother_edu, mother_job, mother_athlete, created_at, updated_at) 
VALUES (22, '13800110022', '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqWjW7e7VJhRj0XkP9QxKxW.KqE9a', '江淮神锋', 'https://api.dicebear.com/7.x/avataaars/svg?seed=player22', 'user', 'active', '许子轩', '2009-08-22', 16, 'male', 178.5, 71.0, 'right', '前锋', '二前锋', 2018, '中国', '安徽', '合肥', '安徽合肥足协青训', 1, '安徽省足球协会', '蓝', 11, 181.0, '15200111128', '本科', '企业老板', 0, 165.0, '15200222239', '本科', '会计师', 0, datetime('now'), datetime('now'));

-- 球员23: 江西南昌 中场
INSERT INTO users (id, phone, password, nickname, avatar, role, status, name, birth_date, age, gender, height, weight, foot, position, second_position, start_year, country, province, city, club, fa_registered, association, jersey_color, jersey_number, father_height, father_phone, father_edu, father_job, father_athlete, mother_height, mother_phone, mother_edu, mother_job, mother_athlete, created_at, updated_at) 
VALUES (23, '13800110023', '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqWjW7e7VJhRj0XkP9QxKxW.KqE9a', '赣鄱指挥官', 'https://api.dicebear.com/7.x/avataaars/svg?seed=player23', 'user', 'active', '郭子墨', '2010-03-10', 15, 'male', 174.0, 66.5, 'both', '中场', '全能中场', 2019, '中国', '江西', '南昌', '江西南昌足协青训', 1, '江西省足球协会', '红', 6, 177.0, '15100111129', '本科', '教师', 0, 163.0, '15100222240', '本科', '医生', 0, datetime('now'), datetime('now'));

-- 球员24: 云南昆明 后卫
INSERT INTO users (id, phone, password, nickname, avatar, role, status, name, birth_date, age, gender, height, weight, foot, position, second_position, start_year, country, province, city, club, fa_registered, association, jersey_color, jersey_number, father_height, father_phone, father_edu, father_job, father_athlete, mother_height, mother_phone, mother_edu, mother_job, mother_athlete, created_at, updated_at) 
VALUES (24, '13800110024', '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqWjW7e7VJhRj0XkP9QxKxW.KqE9a', '春城铁卫', 'https://api.dicebear.com/7.x/avataaars/svg?seed=player24', 'user', 'active', '马子轩', '2009-11-28', 16, 'male', 182.5, 77.0, 'left', '后卫', '中后卫', 2018, '中国', '云南', '昆明', '云南昆明足协青训', 1, '云南省足球协会', '蓝', 4, 185.0, '15000111130', '本科', '建筑工程师', 0, 168.0, '15000222241', '本科', '护士', 0, datetime('now'), datetime('now'));
