-- 球员9-16号数据

-- 球员9: 浙江杭州 中场
INSERT INTO users (id, phone, password, nickname, avatar, role, status, name, birth_date, age, gender, height, weight, foot, position, second_position, start_year, country, province, city, club, fa_registered, association, jersey_color, jersey_number, father_height, father_phone, father_edu, father_job, father_athlete, mother_height, mother_phone, mother_edu, mother_job, mother_athlete, created_at, updated_at) 
VALUES (9, '13800110009', '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqWjW7e7VJhRj0XkP9QxKxW.KqE9a', '杭州小将', 'https://api.dicebear.com/7.x/avataaars/svg?seed=player9', 'user', 'active', '刘子轩', '2010-03-18', 15, 'male', 170.5, 62.0, 'right', '中场', '前腰', 2019, '中国', '浙江', '杭州', '绿城足校', 1, '浙江省足球协会', '绿白', 6, 175.0, '13500111115', '硕士', 'IT工程师', 0, 160.0, '13500222226', '本科', '设计师', 0, datetime('now'), datetime('now'));

-- 球员10: 四川成都 后卫
INSERT INTO users (id, phone, password, nickname, avatar, role, status, name, birth_date, age, gender, height, weight, foot, position, second_position, start_year, country, province, city, club, fa_registered, association, jersey_color, jersey_number, father_height, father_phone, father_edu, father_job, father_athlete, mother_height, mother_phone, mother_edu, mother_job, mother_athlete, created_at, updated_at) 
VALUES (10, '13800110010', '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqWjW7e7VJhRj0XkP9QxKxW.KqE9a', '成都铁卫', 'https://api.dicebear.com/7.x/avataaars/svg?seed=player10', 'user', 'active', '周浩然', '2009-09-05', 16, 'male', 182.0, 75.5, 'left', '后卫', '中后卫', 2018, '中国', '四川', '成都', '成都足协培训中心', 1, '四川省足球协会', '红', 4, 185.0, '13400111116', '本科', '建筑工程师', 1, 168.0, '13400222227', '本科', '会计', 0, datetime('now'), datetime('now'));

-- 球员11: 江苏南京 前锋
INSERT INTO users (id, phone, password, nickname, avatar, role, status, name, birth_date, age, gender, height, weight, foot, position, second_position, start_year, country, province, city, club, fa_registered, association, jersey_color, jersey_number, father_height, father_phone, father_edu, father_job, father_athlete, mother_height, mother_phone, mother_edu, mother_job, mother_athlete, created_at, updated_at) 
VALUES (11, '13800110011', '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqWjW7e7VJhRj0XkP9QxKxW.KqE9a', '南京射手', 'https://api.dicebear.com/7.x/avataaars/svg?seed=player11', 'user', 'active', '吴俊杰', '2010-01-12', 15, 'male', 174.5, 67.0, 'right', '前锋', '影子前锋', 2019, '中国', '江苏', '南京', '江苏苏宁青训', 1, '江苏省足球协会', '蓝', 9, 178.0, '13300111117', '硕士', '销售总监', 0, 165.0, '13300222228', '本科', '人力资源', 0, datetime('now'), datetime('now'));

-- 球员12: 湖北武汉 中场
INSERT INTO users (id, phone, password, nickname, avatar, role, status, name, birth_date, age, gender, height, weight, foot, position, second_position, start_year, country, province, city, club, fa_registered, association, jersey_color, jersey_number, father_height, father_phone, father_edu, father_job, father_athlete, mother_height, mother_phone, mother_edu, mother_job, mother_athlete, created_at, updated_at) 
VALUES (12, '13800110012', '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqWjW7e7VJhRj0XkP9QxKxW.KqE9a', '武汉核心', 'https://api.dicebear.com/7.x/avataaars/svg?seed=player12', 'user', 'active', '郑思远', '2009-07-20', 16, 'male', 178.0, 70.5, 'both', '中场', '全能中场', 2018, '中国', '湖北', '武汉', '武汉卓尔青训', 1, '湖北省足球协会', '橙', 8, 180.0, '13200111118', '本科', '体育教练', 1, 166.0, '13200222229', '本科', '体育老师', 1, datetime('now'), datetime('now'));

-- 球员13: 山东济南 后卫
INSERT INTO users (id, phone, password, nickname, avatar, role, status, name, birth_date, age, gender, height, weight, foot, position, second_position, start_year, country, province, city, club, fa_registered, association, jersey_color, jersey_number, father_height, father_phone, father_edu, father_job, father_athlete, mother_height, mother_phone, mother_edu, mother_job, mother_athlete, created_at, updated_at) 
VALUES (13, '13800110013', '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqWjW7e7VJhRj0XkP9QxKxW.KqE9a', '济南铁闸', 'https://api.dicebear.com/7.x/avataaars/svg?seed=player13', 'user', 'active', '孙浩然', '2010-04-08', 15, 'male', 183.5, 76.0, 'right', '后卫', '右后卫', 2019, '中国', '山东', '济南', '山东鲁能青训', 1, '山东省足球协会', '橙', 2, 186.0, '13100111119', '硕士', '律师', 0, 168.0, '13100222230', '本科', '公务员', 0, datetime('now'), datetime('now'));

-- 球员14: 辽宁沈阳 前锋
INSERT INTO users (id, phone, password, nickname, avatar, role, status, name, birth_date, age, gender, height, weight, foot, position, second_position, start_year, country, province, city, club, fa_registered, association, jersey_color, jersey_number, father_height, father_phone, father_edu, father_job, father_athlete, mother_height, mother_phone, mother_edu, mother_job, mother_athlete, created_at, updated_at) 
VALUES (14, '13800110014', '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqWjW7e7VJhRj0XkP9QxKxW.KqE9a', '沈阳神锋', 'https://api.dicebear.com/7.x/avataaars/svg?seed=player14', 'user', 'active', '杨俊杰', '2009-02-14', 16, 'male', 181.0, 73.5, 'left', '前锋', '中锋', 2018, '中国', '辽宁', '沈阳', '沈阳城市青训', 1, '辽宁省足球协会', '蓝', 20, 184.0, '13000111120', '本科', '公安干警', 0, 170.0, '13000222231', '本科', '护士', 0, datetime('now'), datetime('now'));

-- 球员15: 福建厦门 中场
INSERT INTO users (id, phone, password, nickname, avatar, role, status, name, birth_date, age, gender, height, weight, foot, position, second_position, start_year, country, province, city, club, fa_registered, association, jersey_color, jersey_number, father_height, father_phone, father_edu, father_job, father_athlete, mother_height, mother_phone, mother_edu, mother_job, mother_athlete, created_at, updated_at) 
VALUES (15, '13800110015', '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqWjW7e7VJhRj0XkP9QxKxW.KqE9a', '厦门魔术师', 'https://api.dicebear.com/7.x/avataaars/svg?seed=player15', 'user', 'active', '林逸飞', '2010-09-25', 15, 'male', 173.5, 66.0, 'right', '中场', '进攻中场', 2019, '中国', '福建', '厦门', '厦门青训中心', 1, '福建省足球协会', '白蓝', 7, 176.0, '15900111121', '硕士', '大学教授', 0, 163.0, '15900222232', '硕士', '艺术家', 0, datetime('now'), datetime('now'));

-- 球员16: 陕西西安 后卫
INSERT INTO users (id, phone, password, nickname, avatar, role, status, name, birth_date, age, gender, height, weight, foot, position, second_position, start_year, country, province, city, club, fa_registered, association, jersey_color, jersey_number, father_height, father_phone, father_edu, father_job, father_athlete, mother_height, mother_phone, mother_edu, mother_job, mother_athlete, created_at, updated_at) 
VALUES (16, '13800110016', '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqWjW7e7VJhRj0XkP9QxKxW.KqE9a', '西安城墙', 'https://api.dicebear.com/7.x/avataaars/svg?seed=player16', 'user', 'active', '黄志强', '2009-12-03', 16, 'male', 185.0, 78.5, 'left', '后卫', '左后卫', 2018, '中国', '陕西', '西安', '西安足协青训', 1, '陕西省足球协会', '红黄', 3, 188.0, '15800111122', '本科', '历史老师', 0, 170.0, '15800222233', '本科', '图书管理员', 0, datetime('now'), datetime('now'));
